package cgpa.generator;


import static cgpa.generator.Credit.getDept;
import static cgpa.generator.Credit.getTotal_credit;
import cgpa.generator.DataOutput;
import cgpa.generator.Fail;
import java.sql.*;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SCC
 */
public class DataInput3 extends javax.swing.JFrame {

    /**
     * Creates new form DataInput5
     */
    Connection con =  null;//connect.connectdb();
    PreparedStatement ps = null;
    ResultSet rs = null;
    String cgpa_s;
    double cgpa_d;
    
    public DataInput3() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Please enter your Subject score & course credit sequentially");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 44, -1, -1));

        jLabel2.setText("Subject Score :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel3.setText("Subject Score :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel4.setText("Subject Score :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel5.setText("Subject Score :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel6.setText("Subject Score :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel7.setText("Subject Score :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jLabel8.setText("Subject Score :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        jLabel10.setText("Course Credit :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        jLabel11.setText("Course Credit :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        jLabel12.setText("Course Credit :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));

        jLabel13.setText("Course Credit :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));

        jLabel14.setText("Course Credit :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        jLabel15.setText("Course Credit :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, -1, -1));

        jLabel16.setText("Course Credit :");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 122, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 122, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 122, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 122, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 122, -1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 122, -1));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 122, -1));
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 125, -1));
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 125, -1));
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 125, -1));
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 125, -1));
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 125, -1));

        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 125, -1));
        getContentPane().add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 125, -1));

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setText("NEXT");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 54, -1));

        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setText("RESET");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 60, -1));

        jButton3.setBackground(new java.awt.Color(153, 255, 255));
        jButton3.setText("BACK");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 50, -1));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 120, -1));

        jLabel9.setText("NAME :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cgpa/generator/BG1_1.jpg"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 450));

        setSize(new java.awt.Dimension(626, 489));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    int Piyal = 1, Mushroof = 1;
     public double compare(double grade){
        if(grade >= 80)
            return 4.00;
        else if(grade >= 75)
            return 3.75;
        else if(grade >= 70)
            return 3.50;
        else if(grade >= 65)
            return 3.25;
        else if(grade >= 60)
            return 3.00;
        else if(grade >= 55)
            return 2.75;
        else if(grade >= 50)
            return 2.50;
        else if(grade >= 45)
            return 2.25;
        else if(grade >= 40)
            return 2.00;
        else
        {
            return 0;
        }
    }
    public void cheak(String str) {
            try {
                double num = Double.parseDouble(str);
                Piyal = 1;
            } catch (Exception e) {
                JOptionPane.showMessageDialog(DataInput3.this, "Enter value / proper value", "ERROR", 0);
                Mushroof = 0;
            }
    }
    
    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        //Cheaking values
        cheak(jTextField1.getText());
        cheak(jTextField2.getText());
        cheak(jTextField3.getText());
        cheak(jTextField4.getText());
        cheak(jTextField5.getText());
        cheak(jTextField6.getText());
        cheak(jTextField7.getText());

        cheak(jTextField9.getText());
        cheak(jTextField10.getText());
        cheak(jTextField11.getText());
        cheak(jTextField12.getText());
        cheak(jTextField13.getText());
        cheak(jTextField14.getText());
        cheak(jTextField15.getText());

       if(Piyal != 0 && Mushroof != 0){
        //For Subject
        String s1 = jTextField1.getText();
        //int n1 = Integer.parseInt(s1);
        double n1 = Double.parseDouble(s1);
        String s2 = jTextField2.getText();
        double n2 = Double.parseDouble(s2);
        String s3 = jTextField3.getText();
        double n3 = Double.parseDouble(s3);
        String s4 = jTextField4.getText();
        double n4 = Double.parseDouble(s4);
        String s5 = jTextField5.getText();
        double n5 = Double.parseDouble(s5);
        String s6 = jTextField6.getText();
        double n6 = Double.parseDouble(s6);
        String s7 = jTextField7.getText();
        double n7 = Double.parseDouble(s7);


        
        //For Credit
        String sc1 = jTextField9.getText();
        double c1 = Double.parseDouble(sc1);
        String sc2 = jTextField10.getText();
        double c2 = Double.parseDouble(sc2);
        String sc3 = jTextField11.getText();
        double c3 = Double.parseDouble(sc3);
        String sc4 = jTextField12.getText();
        double c4 = Double.parseDouble(sc4);
        String sc5 = jTextField13.getText();
        double c5 = Double.parseDouble(sc5);
        String sc6 = jTextField14.getText();
        double c6 = Double.parseDouble(sc6);
        String sc7 = jTextField15.getText();
        double c7 = Double.parseDouble(sc7);


        //For grade cheaking
        double g1 = compare(n1);
        double g2 = compare(n2);
        double g3 = compare(n3);
        double g4 = compare(n4);
        double g5 = compare(n5);
        double g6 = compare(n6);
        double g7 = compare(n7);


        //Fail cheaking
        if(g1 == 0 || g2 == 0 ||g3 == 0 || g4 == 0 || g5 == 0 || g6 == 0 || g7 == 0)
        {
            this.setVisible(false);
            new Fail().setVisible(true);
        }
         else if(n1 < 0 || n2 < 0 || n3 < 0 || n4 < 0 || n5 < 0 || n6 < 0 || n7 <0)
            {
                JOptionPane.showMessageDialog(DataInput3.this, "Enter proper value", "ERROR", 0);
            }
        else if(n1 > 100 || n2 > 100 || n3 > 100 || n4 > 100 || n5 > 100 || n6 > 100 || n7 > 100)
            {
                JOptionPane.showMessageDialog(DataInput3.this, "Enter proper value", "ERROR", 0);
            }
        else
        {
        //Grade calculation
        double cgpa = (g1*c1 + g2*c2 + g3*c3 + g4*c4 + g5*c5 + g6*c6 + g7*c7)/getTotal_credit();
        int cgpa_int = (int) (cgpa*1000);
        cgpa_d = (double) (cgpa_int/1000.00);
        if(cgpa_d > 4)
        {
            JOptionPane.showMessageDialog(DataInput3.this, "Enter proper value in Credit", "ERROR", 0);
        }
        else{
        cgpa_s = String.valueOf(cgpa_d);
        this.setVisible(false);
        new DataOutput(cgpa_s).setVisible(true);
        //setVisible(false);
        }
        }
       }
       Piyal = 1; Mushroof = 1;
       
       if(cgpa_d > 0)
        {
        try {
            try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/CGPA_info", "piyal", "204204204");
                } catch (SQLException ex) {
            System.out.println("Coonect 1st");
            }
            
            //String name = jTextField1.getText();

            String sql = "INSERT INTO PIYAL.STUDENTS_CGPA VALUES (?, ?, ?)";
            ps = con.prepareStatement(sql);

            ps.setString(1, jTextField8.getText());
            ps.setString(2, cgpa_s);
            ps.setString(3, getDept());
            
            ps.executeUpdate();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(DataInput3.this, "Something wrong. Try Again", "ERROR", 0);
    }
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new Display2().setVisible(true);
        this.setVisible(false);
        
        Piyal = 1; Mushroof = 1;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(" ");
        jTextField2.setText(" ");
        jTextField3.setText(" ");
        jTextField4.setText(" ");
        jTextField5.setText(" ");
        jTextField6.setText(" ");
        jTextField7.setText(" ");
        jTextField8.setText(" ");
        jTextField9.setText(" ");
        jTextField10.setText(" ");
        jTextField11.setText(" ");
        jTextField12.setText(" ");
        jTextField13.setText(" ");
        jTextField14.setText(" ");
        jTextField15.setText(" ");
        Piyal = 1; Mushroof = 1;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataInput3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataInput3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataInput3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataInput3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataInput3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
